In [53]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [54]:
iris_dataset = load_iris()
iris_dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [55]:
df = pd.DataFrame(iris_dataset.data, columns=iris_dataset.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [56]:
df.shape

(150, 4)

In [57]:
df.to_csv('iris.csv')

In [58]:
random_df = pd.DataFrame(np.random.rand(40,5))
random_df

           0         1         2         3         4
0   0.433317  0.329328  0.703114  0.903677  0.545233
1   0.084127  0.579084  0.881535  0.071332  0.127920
2   0.200016  0.881662  0.491152  0.017098  0.414825
3   0.181882  0.220471  0.001661  0.533488  0.193164
4   0.954372  0.134940  0.621643  0.581479  0.475454
5   0.816405  0.430734  0.555141  0.734594  0.664598
6   0.388413  0.676970  0.172902  0.878055  0.791575
7   0.748621  0.766502  0.255432  0.138903  0.409212
8   0.155773  0.089565  0.526233  0.668681  0.058157
9   0.021268  0.620589  0.563022  0.304299  0.929440
10  0.384491  0.773095  0.434124  0.663965  0.204524
11  0.344540  0.262776  0.825581  0.785790  0.753688
12  0.830890  0.950076  0.043764  0.759190  0.639680
13  0.533657  0.046132  0.409277  0.252874  0.406125
14  0.168742  0.888198  0.745739  0.230905  0.768895
15  0.134287  0.338267  0.129603  0.839293  0.765378
16  0.991652  0.930812  0.200627  0.917383  0.955006
17  0.237561  0.955716  0.719098  0.768842  0.363200
18  0.035951  0.748293  0.855758  0.148438  0.643904
19  0.586641  0.028654  0.039648  0.279513  0.719500
20  0.847023  0.017473  0.356012  0.297868  0.025504
21  0.889058  0.127024  0.371431  0.392378  0.703244
22  0.827618  0.110875  0.402920  0.380890  0.310065
23  0.697496  0.405407  0.591847  0.623544  0.807562
24  0.751797  0.083979  0.326131  0.547749  0.485491
25  0.257168  0.763411  0.517613  0.835689  0.211003
26  0.314933  0.315841  0.359638  0.965324  0.738981
27  0.160234  0.933106  0.340918  0.448882  0.120930
28  0.642085  0.767876  0.286821  0.522602  0.799894
29  0.096644  0.451965  0.357525  0.115761  0.361993
30  0.490608  0.271839  0.699177  0.379039  0.636043
31  0.153262  0.047264  0.666351  0.643616  0.370714
32  0.953520  0.449738  0.815608  0.973849  0.132152
33  0.222134  0.981708  0.909704  0.026554  0.899636
34  0.984865  0.202022  0.585098  0.742796  0.611327
35  0.245277  0.378877  0.590196  0.294918  0.053351
36  0.910558  0.500970  0.411995  0.602967  0.806898
37  0.048651  0.624312  0.080707  0.798529  0.704305
38  0.963537  0.984706  0.420293  0.772908  0.881821
39  0.636592  0.892927  0.051611  0.882002  0.345450

In [59]:
df.shape

(150, 4)

In [60]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [61]:
df.tail()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [63]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [64]:
df.value_counts('petal width (cm)')

petal width (cm)
0.2    29
1.3    13
1.5    12
1.8    12
1.4     8
2.3     8
0.3     7
1.0     7
0.4     7
2.0     6
2.1     6
1.9     5
0.1     5
1.2     5
1.6     4
2.2     3
2.4     3
1.1     3
2.5     3
1.7     2
0.6     1
0.5     1
Name: count, dtype: int64

In [65]:
df.groupby('petal width (cm)').mean()

                  sepal length (cm)  sepal width (cm)  petal length (cm)
petal width (cm)
0.1                        4.820000          3.360000           1.380000
0.2                        4.972414          3.379310           1.444828
0.3                        4.971429          3.328571           1.428571
0.4                        5.300000          3.785714           1.571429
0.5                        5.100000          3.300000           1.700000
0.6                        5.000000          3.500000           1.600000
1.0                        5.414286          2.371429           3.628571
1.1                        5.400000          2.466667           3.566667
1.2                        5.780000          2.740000           4.240000
1.3                        5.884615          2.746154           4.176923
1.4                        6.325000          2.912500           4.637500
1.5                        6.183333          2.816667           4.658333
1.6                        6.375000          3.100000           5.025000
1.7                        5.800000          2.750000           4.750000
1.8                        6.400000          2.941667           5.333333
1.9                        6.340000          2.680000           5.320000
2.0                        6.650000          3.016667           5.550000
2.1                        6.916667          3.033333           5.783333
2.2                        6.866667          3.200000           6.033333
2.3                        6.912500          3.087500           5.700000
2.4                        6.266667          3.100000           5.433333
2.5                        6.733333          3.400000           5.933333

In [66]:
df.groupby('petal width (cm)').max()

                  sepal length (cm)  sepal width (cm)  petal length (cm)
petal width (cm)
0.1                             5.2               4.1                1.5
0.2                             5.8               4.2                1.9
0.3                             5.7               3.8                1.7
0.4                             5.7               4.4                1.9
0.5                             5.1               3.3                1.7
0.6                             5.0               3.5                1.6
1.0                             6.0               2.7                4.1
1.1                             5.6               2.5                3.9
1.2                             6.1               3.0                4.7
1.3                             6.6               3.0                4.6
1.4                             7.0               3.2                5.6
1.5                             6.9               3.2                5.1
1.6                             7.2               3.4                5.8
1.7                             6.7               3.0                5.0
1.8                             7.3               3.2                6.3
1.9                             7.4               2.8                6.1
2.0                             7.9               3.8                6.7
2.1                             7.6               3.3                6.6
2.2                             7.7               3.8                6.7
2.3                             7.7               3.4                6.9
2.4                             6.7               3.4                5.6
2.5                             7.2               3.6                6.1

In [67]:
df.count()

sepal length (cm)    150
sepal width (cm)     150
petal length (cm)    150
petal width (cm)     150
dtype: int64

In [68]:
df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [69]:
df.std()

sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64

In [70]:
df.min()

sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64

In [71]:
df.max()

sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64

In [72]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [73]:
df['price'] = df['sepal length (cm)']*df['petal width (cm)'] *100
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),price
0,5.1,3.5,1.4,0.2,102.0
1,4.9,3.0,1.4,0.2,98.0
2,4.7,3.2,1.3,0.2,94.0
3,4.6,3.1,1.5,0.2,92.0
4,5.0,3.6,1.4,0.2,100.0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,1541.0
146,6.3,2.5,5.0,1.9,1197.0
147,6.5,3.0,5.2,2.0,1300.0
148,6.2,3.4,5.4,2.3,1426.0
149,5.9,3.0,5.1,1.8,1062.0

In [74]:
df = df.drop(index=0,axis=0)
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),price
1,4.9,3.0,1.4,0.2,98.0
2,4.7,3.2,1.3,0.2,94.0
3,4.6,3.1,1.5,0.2,92.0
4,5.0,3.6,1.4,0.2,100.0
5,5.4,3.9,1.7,0.4,216.0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,1541.0
146,6.3,2.5,5.0,1.9,1197.0
147,6.5,3.0,5.2,2.0,1300.0
148,6.2,3.4,5.4,2.3,1426.0
149,5.9,3.0,5.1,1.8,1062.0

In [75]:
df = df.drop(columns='sepal width (cm)',axis = 1)
df

     sepal length (cm)  petal length (cm)  petal width (cm)   price
1                  4.9                1.4               0.2    98.0
2                  4.7                1.3               0.2    94.0
3                  4.6                1.5               0.2    92.0
4                  5.0                1.4               0.2   100.0
5                  5.4                1.7               0.4   216.0
..                 ...                ...               ...     ...
145                6.7                5.2               2.3  1541.0
146                6.3                5.0               1.9  1197.0
147                6.5                5.2               2.0  1300.0
148                6.2                5.4               2.3  1426.0
149                5.9                5.1               1.8  1062.0

[149 rows x 4 columns]

In [76]:
df.iloc[4]

sepal length (cm)      5.4
petal length (cm)      1.7
petal width (cm)       0.4
price                216.0
Name: 5, dtype: float64

In [77]:
df.iloc[:,0]

1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 149, dtype: float64

In [78]:
df.corr()

,sepal length (cm),petal length (cm),petal width (cm),price
sepal length (cm),1.000000,0.871281,0.816961,0.883993
petal length (cm),0.871281,1.000000,0.962423,0.963137
petal width (cm),0.816961,0.962423,1.000000,0.986165
price,0.883993,0.963137,0.986165,1.000000